avatar: /images/avatar.png

pages:
  about: /about/
  tags: /tags/
  links: /links/

mathjax:
  enabled: true
  smartload: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
